#!/bin/bash
# Author: Chung
# Date Created: 26/05/2021
# Description: Run basic linux tasks
# Date Modified: 26/05/2021

echo 
echo This script will run a few basic tasks
echo
pwd
echo
ls
echo
whoami
echo
date
echo
cal
echo
touch a b c
echo End of script

