#!/bin/bash
# Author: Chung Byungjae
# Date: 08/08/2020
# Description: This script will pull only Warn messages from /var/log/syslog
# Modified: 08/08/2020

grep -i warn /home/chung/study-shellscript/professional-sripts/syslog
