#!/bin/bash

FILES="/etc/passwd
/etc/group
/etc/shadow
/etc/nsswitch.conf
/etc/sshd_ssh_config
/etc/fake"

echo 

for file in $FILES
do
	if [ ! -e $file ]
	then
	echo $file do not exist
	echo 
	fi
done
