#!/bin/bash
# Author: Chung ByungJae
# Date: 06/05/2021
# Description: This script will ping a remote host and notify
# Modified: 06/05/2021

hosts="192.168.1.1"
ping -c1 $hosts &> /dev/null
	if [ $? -eq 0 ]
	then
	echo
	echo $hosts OK
	else
	echo
	echo $hosts NOT OKAY
	fi

